=== m instruction set

The instruction set (`inst_set`) specifies a collection of reusable objects and functions and is what is commonly called 
a _package_ (i.e. a library, an API, a module, etc.). In [metatron], an `inst_set` is defined as the 4-tuple

++++
\begin{align*}
\texttt{inst_set} \in \left(\texttt{TYPE} \times \texttt{INST} \times \texttt{REWRITE} \times \texttt{PARSER}\right),
\end{align*}
++++
where each component of the tuple is a set of the specified kind. To function properly, [metatron] requires, a minimum,
two instruction sets: `m` and `mach`. This section will discuss `m`.

The core instruction set of metatron is `m`. The components of `m` are available at `/m/#`. To dereference the pattern `/m/#/`, `*` is used,
where `*(uri)` is the sugar form of the instruction `from(uri)` and is perhaps the most important instruction in [metatron].

++++
<!--🐖
*/mnt/lang/m
*/m/#
-->
++++

++++
<!-- 🐓 -->
++++


[cols="1m,3m,4",separator="|"]
|===
|type |example |description

|/m/bool | bool{2}::{true,false}   | a 2-member boolean type
|/m/int  | int::123456             | a 64-bit integer type
|/m/real | real::-123.456          | a 64-bit double type
|/m/str  | str::'metatron'         | a string of characters
|/m/uri  | uri::\<http://a/b/c>    | the infinite set of all uris
|/m/lst  | lst::[1,2,3,4]          | a poly of ordered `objs`
|/m/rec  | rec::[k1\=>v1,k2\=>v2]    | a poly of `obj` key/value pairs
|/m/inst | plus?int\<=int::(2)     | a function mapping dom to rng
|/m/code | a().b(c,d).e(f)         | a chain of nested `insts`
|/m/type | int::T[is(gt(0))]       | a specification of constraint on a base-type
|/m/fail | fail::[problem,error]   | a meta-`obj` accessible via `catch()`
|===

++++
<!-- ./main_runner.out
threadx[[ /
  halt=>false, /
  delay=>nat[0], /
  loop=>from(|a,0).plus(1).to(a).print(_). /
         [is(gt(10)) => |true.to(abc/halt)]>-]]@abc
@abc.spawn()
-->
++++