[discrete]
== HTTP Space

[discrete]
=== HTML Type

The type `html::T < rec::T` (a refinement of `rec::T`) represents an https://en.wikipedia.org/wiki/HTML[HTML] document.

++++
<!-- 🐖
html::T                                           [-- <1>
*<http://phaseshift.studio/>                      [-- <2>
*<http://phaseshift.studio/html/head/title>       [-- <3>
*<http://phaseshift.studio>.as(str::T)            [-- <4>
-->
++++
<1> The structural definition of `html::T`.
<2> Retrieve the `index.html` of the website. Content-type yields `text/html` which for metatron maps to `html::T`.
<3> The `title` element of the `index.html` of the website.
<4> The `index.html` of the website as a `str::T` (`string => rec => string`).


[discrete]
=== Accessing REST APIs

When a https://en.wikipedia.org/wiki/REST[REST] endpoint has a URL address that matches an `httpspace` pattern, the REST resources can be used in metatron. This is possible because `httpspace` transforms data "in the wild" (e.g. `application/json`) into an isomorphic `obj`. If the newly mapped `obj` is typed, then it inherits the instructions for that type as defined by the `instset` of the type. As such, REST resources can be enriched/typed to serve as active computational objs in metatron.

A https://localai.io/[LocalAI] service will serve to demonstrate how to leverage foreign resources in metatron. LocalAI exposes an https://www.openapis.org/[OpenAPI]-compliant endpoint at `http://localhost:8088/v1` (this is specific to the author's local deployment of LocalAI).

++++
<!-- 🐖 
*<http://localhost:8088/v1>                        [-- <1>
*<http://localhost:8088/v1/models>                 [-- <2>
*<http://localhost:8088/v1/models/data/0/id>       [-- <3>
*<http://localhost:8088/api/models/config-json/${  /
  *<http://localhost:8088/v1/models/data/0/id>}>   [-- <4>
-->
++++
<1> No result, but also no connection `fail::T`. The endpoint is alive.
<2> The `/models` resource contains a list of all LLM models available for use in LocalAI.
<3> Traversing the data within the resource is a function of extending the URI accordingly.
<4> Using URI template parameters to fetch more information about the model.

Once the desired REST resource has been accessed, it's possible to map the resource into a form that meets the structural requirements of an mtron `type`. In doing so, the resource then acquires the behaviors defined in the type's respective `instset`. For this example, that `instset` is `/m/llm`.

++++
<!-- 🐖
*/m/llm/model                      [-- <1>
*/m/llm/inst/+?dom=model
-->
++++
<1> The `model::T` type in `/m/llm`.
<2> The `/m/llm` instructions with a domain of `model::T`  (an object oriented perspective -- `obj.f()`).

When the REST resource is manipulated to fit the structural specification of `model::T`, then  `http://localhost:8088/v1/models/data/0` can be the source of `chat?#\<=model`.


++++
<!-- 🐖
*<http://localhost:8088/v1/models/data/0>>-.           /
  -<[name=>>>id.as(uri::T),                            /
     type=>>>object.as(uri::T),                        /
     provider=>|!*/sys/space/localai].as(model::T)     /
  .chat('are you there?')                       [-- <1>
-->
++++
<1> The OpenAPI `application/json` resource is morphed into a metatron `model::T` and then the model is `chat`ted with.


