[discrete]
== Instructions

++++
<!--
┌ ├ ┐ └ ┘ │ ┤ ─ ⋰ ⋱ ⮝ ⮞ ⮜ ⮟
-->
++++

mtron programs are composed using computational primitives called **instructions** (`inst`). Instructions are organized into libraries called **instruction sets** (`instset`) -- https://en.wikipedia.org/wiki/Domain_of_discourse[domains of discourse]. Mathematically, every instruction is a **function** written according to the form:

[source,mtron]
----
 tid{c}?rng<=dom(args){ code }@vid                                                  
  │  │   │      │ │  │  │    │   │                                                   
  │  │   └──┬───┘ └─┬┘  └─┬──┘   │                                                   
  │  │      │       │     │      └────⮞ location: instance location (addr)                
  │  │      │       │     └───────────⮞ code: instruction body is a tree of instructions (impl)        
  │  │      │       └─────────────────⮞ arguments: dynamic parameterizations (args)    
  │  │      └─────────────────────────⮞ domain/range: the incoming (lhs) and outgoing (rhs) obj types                
  │  └────────────────────────────────⮞ coefficient: the magnitude of the instruction upon the rhs              
  └───────────────────────────────────⮞ the type id of the instruction (opcode)
----

[.card]
--
The instruction template above represents the typical instruction with `rng\<=dom` and `{c}` sugar syntax being used. 
However, note that the dom/rng and coefficient sugars ultimately compile to URI query parameters. 
When fully parsed to a legal URI, the instruction signature is denoted:

[source,mtron,role="center-code"]
----
inst?dom=a&rng=b&c=x,y
----

Instruction query parameters are similar in function to https://en.wikipedia.org/wiki/Java_annotation[method annotations]. Query parameters encode metadata which can
aid the compiler instruction selection, enable code path compression, facilitate polymorphic dispatch, support lifted monadic processing, maintain runtime profiling statistics, and more.
--

[.discrete]
=== obj propagation mechanics

Every instruction maps a **left hand side** `obj` (`lhs`) to a **right hand side** `obj` (rhs). Many-to-one, one to many, and many-to-many mappings are possible as an `obj` is an element in the power set of all `objs`. Thus, `{1,2,3}` is an `obj` with type `int{3}`. Programmatically, what is passed between instructions is a single stream `obj` which guarantees that there is always an rhs `obj` for every lhs `obj` regardless of failure or emptiness.

\begin{align*}
\text{obj} \in \mathcal{P}(\text{obj})
\end{align*}

It is important to understand the mechanics of instruction evaluation. Every instruction follows the same pattern. When a lhs `obj` is applied to an `inst` obj, the first thing that happens is the arguments of the `inst` are resolved. This is perhaps best described with an example.

++++
<!-- 🐖 
1.plus(2)          [-- <1>
1.plus(_)          [-- <2>
1.plus(plus(2))    [-- <3>
1.map(bool::T)     [-- <4>
1.as(bool::T)      [-- <5>
-->
++++

<1> `1` is applied to `2` and then `1` is added to `2` to yield `3`. (expected)
<2> `1` is applied to the identity function to yield `1` and then `1` is added to `1` to yield `2`.
<3> `1` is applied to the instruction `plus(2)` to yield `3` and then `1` is added to `3` to yield `4`.
<4> `1` is applied to the type `bool::T` to yield `noobj` as types serve as stream predicates.
<5> `1` is applied to `bool::T` to yield `noobj` but then is operated within the code of `as()` to emit `bool::true`.

The key point is that *call* objs (`inst`, `code`, `noobj`, and `type`) have a dynamic domain and range. Constant
`objs` (non-call objs) also have a domain and range. For instance, the verbose representation of `int::1` is `int?int\<=#{?}::1`. 
This states that every lhs `obj` or `noobj` (`+#+{+?+}`) that is applied to `1`, yields a single rhs `int`; namely `1`. In this way, constants are functions (calls), though not interesting because they always return the same value regardless of input.

The diagram below demonstrates how a lhs `obj` percolates through an `inst` to where ultimately, at the end of the last `inst` of code the resultant rhs `obj` is emitted.

[source,mtron,role="center-code"]
----
     ┌────────────────┐                                       
 ┌───┴───────┐        │       ┌──┐     ┌────────┐            
 │           ▼ 1      ▼ 2     │  ▼ 4   │      6 ▼            
lhs => inst(arg1,...,argN){ inst1...instN } => rhs           
 │                          3 ▲   │  ▲ 5                       
 └────────────────────────────┘   └──┘
----



[discrete]
=== stacks and frames

Every logical thread has a `/m/space/stack` patterned `<+/#>`. The current stack of the mtron code processing this documentation is available in the collapsed accordian below. The state of this stack is the result of all the processing thus far up to this point in the documentation. Local variables from other parts of the documentation will be noticed. Furthermore, note the `boot/` branch. This stores the data provided by the user and derived by the bootloader at startup.

.the objs of the doc processors stack
[%collapsible]
====

++++
<!-- 🐖 
*<+/#/>
-->
++++

====

[source,mtron,role="center-code"]
----
                                                  
 lhs    inst(arg1,...,argN){ inst1...instN }     rhs           
  │         │            │  │             │       ▲             
  │push     └─────┬──────┘  └─────────────┘    pop│            
┌─┼───────────────┼──────┐     inst body          │     
│ │           inst│frame │                       ┌─┐         
│ ▼               │      ├──────────────────────►│X│         
│ stack           ▼      │                       └─┘         
└────────────────────────┘                                     
----


When an instruction is called, the associated https://en.wikipedia.org/wiki/Parameter_(computer_programming)[arguments] have the lhs `obj` applied and the result of the application is pushed onto the stack -- accessible through reference for entirety of the 
`inst` code block. From this architecture, the following `inst` forms are made available for use.


[indent=0,subs="verbatim,attributes",role="primary"]
.positional args
=====

[.card-tight]
--
[stem]
++++
\large \tt{obj}_\tt{lhs} \cdot f(\color{yellow}{\__{0}}, \color{yellow}{\__{1}},\ldots,\color{yellow}{\__{n}}) \mapsto \tt{obj}_\tt{rhs}
++++
--

The arguments are captured as a `lst` and are accessed via their position furi.
For example, `*<0>` references the first argument, `+*+<1>` the second argument, so on and so forth. Note that for single digit numbers, the uri `< >` wrapper isn't required and the above can be written as `*0`, `*1`, etc.

In the example below, the user defined instruction `band` filters out lhs `objs` not within the provided range (min/max).
Given the filtering behavior of the instruction, the signature of `band` is `int{?}\<=int`. That is, it accepts a single
`int` and return either `noobj` or the `int`.

++++
<!-- 🐖 
band -> |inst?int{?}<=int(_,_){ is(and(gte(*0),lte(*1))) }
3.band(2,8)                                [-- <1>
10.band(2,8)                               [-- <2>
-->
++++

<1> `3` is within the band `[2,8]` and thus, `3` is the result, satisfying the `inst` range `int{?}`.
<2> `10` is not within the band `[2,8]` and thus, the result is `noobj` which satisfies the `inst` range `int{?}`.
=====

[indent=0,subs="verbatim,attributes",role="secondary"]
.named args
=====

[.card-tight]
--
[stem]
++++
\large \tt{obj}_\tt{lhs} \cdot f(\color{yellow}{a_1} \Rightarrow x, \color{yellow}{a_2} \Rightarrow y,\ldots,a_n) \mapsto \tt{obj}_\tt{rhs}
++++
--

When the arguments are provided in a `rec` form, the key of each relation of the `rec` is a https://en.wikipedia.org/wiki/Named_parameter[named argument]. Named
arguments are resolved from the stack via their furi name.

++++
<!-- 🐖 
band -> |inst?int{?}<=int(min=>_,max=>_){ is(and(gte(*min),lte(*max))) }
3.band(min=>2,max=>4)                 [-- <1>
3.band(2,8)                           [-- <2>
3.band(max=>8,min=>2)                 [-- <3>
'abc'.band(2,8)                       [-- <4>
-->
++++

<1> The argument's name is it's reference on the stack.
<2> If the argument name isn't provided, then it's position in the argument list determines its name.
<3> When arguments are named, they can be written in any order.
<4> The domain of `band` is `int`.
Note where the error is thrown when `str['abc']` is provided.
=====

[indent=0,subs="verbatim,attributes",role="secondary"]
.default args
=====

[.card-tight]
--
[stem]
++++
\large \tt{obj}_\text{lhs} \cdot f(a_1 \Rightarrow \color{yellow}{else(x)},a_2 \Rightarrow \color{yellow}{else(y)},\ldots,a_n) \mapsto \tt{obj}_\tt{rhs}
++++
--

The `else` instruction has numerous uses. With respect to instruction arguments, the `else` instruction provides the user
the ability to express
https://en.wikipedia.org/wiki/Default_argument[default arguments].
If the incoming `obj` to `else` is `noobj`, then `else` returns it's argument, otherwise it returns the incoming lhs `obj`.

++++
<!-- 🐖 
band -> |inst?int{?}<=int(min=>else(2),max=>else(8)){ is(and(gte(*min),lte(*max))) }
1.band(min=>1)                        [-- <1>
10.band()                             [-- <2>
{2,3,4,5}.band(min=>3,max=>4)         [-- <3>
-->
++++

<1> No `max` is provided, so the default value of `8` is used.
<2> No `min` nor `max` is provided, so the defaults `2` and `8`, respectively are used.
<3> When arguments are provided, the default values are not used.
=====

[indent=0,subs="verbatim,attributes",role="secondary"]
.typed args
=====

[.card-tight]
--
[stem]
++++
\large \tt{obj_{\text{lhs}} \cdot f(a_1 \Rightarrow \color{yellow}{?type_1}, a_2 \Rightarrow \color{yellow}{?type_2},\ldots,a_n \Rightarrow \color{yellow}{?type_3}) \mapsto obj_{rhs}}
++++
--

The previous examples made use of the polymorphic `id` instruction (sugar'd `_`). It's important to realize that an argument
can be any arbitrary `obj` (thus, `code`). Type arguments are the means by which instruction arguments are typed.

++++
<!-- 🐖 
nat  -> int::T[?>0]          [-- <1>
band -> |inst?int{?}<=int(min=>?nat::T,max=>?nat::T){ is(and(gte(*min),lte(*max))) }
15.band(10,20)              [-- <2>
-15.band(-20,-10)           [-- <3>
band -> |inst?int{?}<=int(min=>as(nat::T),max=>as(nat::T)){ is(and(gte(*min),lte(*max))) }
15.band(10,20)              [-- <4>
-15.band(-20,-10)           [-- <5>
band -> |inst?int{?}<=int(min=>?nat::T.else(fail()),max=>?nat::T.else(fail())){ is(and(gte(*min),lte(*max))) }
15.band(10,20)              [-- <6>
-15.band(-20,-10)           [-- <7>
band -> |inst?int{?}<=int(min=>?nat::T.else(-100),max=>?nat::T.else(100)){ is(and(gte(*min),lte(*max))) }
15.band(10,20)              [-- <8>
-15.band(-20,-10)           [-- <9>
-->
++++

<1> A `nat` is an `int` greater than zero.
<2> Argument name uniqueness does not consider query parameters.
<3> The `?nat` query parameter requires the respective argument be some stem:[n \in \mathbb{N}].
=====

[indent=0,subs="verbatim,attributes",role="secondary"]
.anonymous inst
=====

[.card-tight]
--
[stem]
++++
\large \tt{obj}_\tt{lhs} \cdot \color{yellow}{\lambda}(a_1 \Rightarrow x, a_2 \Rightarrow y,\ldots,a_n) \mapsto \tt{obj}_\tt{rhs}
++++
--

An untyped `inst` is an anonymous `inst` and behaves analogously to an
https://en.wikipedia.org/wiki/Anonymous_function[anonymous function] in other programming environments.
Anonymous `insts` can be both defined and evaluated in the same expression to provide
https://en.wikipedia.org/wiki/Immediately_invoked_function_expression[immediately invoked function expression] semantics.
Like any `inst`, anonymous `inst` arguments are scoped to the value of the `inst`, providing
https://en.wikipedia.org/wiki/Scope_(computer_science)#Block_scope[block-scope] semantics.
Finally, a degenerate anonymous `inst` with no specified variable frame is simply `bcode`.

++++
<!-- 🐖 
10.(min=>2,max=>8){ is(and(gte(*min),lte(*max))) }                [-- <1>
10.(min=>minus(1),max=>plus(1)){ is(and(gte(*min),lte(*max))) }   [-- <2>
10.(min=>2,max=>8){ is(and(gte(*bad_min),lte(*bad_max))) }        [-- <3>
10.(){ is(and(gte(*min),lte(*max))) }                             [-- <4>
10.is(and(gte(minus(1)),lte(plus(1))))                            [-- <5>
-->
++++

<1> The unnamed "band" `inst` is evaluated in line.
<2> `min` and `max` are computed dynamically relative to the input.
<3> The `inst` value is referencing undefined frame variables.
<4> An anonymous `inst` is compiled to an `obj` filter-`inst`.
<5> When arguments are embedded in the value, then the `inst` is simply `bcode`.
=====


[indent=0,subs="verbatim,attributes",role="secondary"]
.contextualargs
=====

++++
<!-- 🐖 
is_divisible -> |is_divisble?bool<=int(by?int=>_)[mod(*by).eq(0)]
10.is_divisible(2)
10.is_divisible('abc')
-->
++++
=====

[indent=0,subs="verbatim,attributes",role="secondary"]
.dependent args
=====

[.card-tight]
--
[stem]
++++
\large \tt{obj}_\tt{in}.f(a_1 \Rightarrow x,a_2 \Rightarrow \color{yellow}{g(*a_1)},\ldots,a_n) \mapsto \tt{obj}_\tt{out}
++++
--

If an argument's type is dependent on the value of another argument, then the argument is a https://en.m.wikipedia.org/wiki/Dependent_type[dependent argument].

++++
<!-- 🐖 
band -> |band?int{?}<=int(min=>_,max=>is(gt(*min)).else(*min.plus(1)))[is(gte(*min)).is(lte(*max))]
2.band(min=>1,max=>1)                 [-- <1>
-->
++++

<1> ...
=====

[indent=0,subs="verbatim,attributes",role="secondary"]
.refined args
=====

++++
<!-- 🐖 
is_divisible -> |is_divisble?bool<=int(by?int=>is(neq(0)).else(print('error').map(1)))[mod(*by).eq(0)]
10.is_divisible(2)
10.is_divisible('abc')
-->
++++
=====




An `inst` to create `int` triples can be written:

++++
<!-- 🐖
triple -> |inst?lst<=int{3}(){>-[,]}
{1,2,3,4,5,6}.triple()
-->
++++

[NOTE]
====
The `|` token is synatic sugar for the `block` inst. A blocked instruction prevents the application of the `lhs` to the `inst` args and `inst` code.
This ensures the uri `triple` is not applied to the `inst` prior to the uri being bound as the reference (`->`). Without block, the result of applying `triple` to `inst` would be what `triple` is bound to. In this particular instance, `triple` would reference a `fail` obj.

++++
<!-- 🐖
triple -> inst?lst[int,int,int]<=int{3}(){>-[,]}
*triple
-->
++++

====

A stricter representation leveraging polymorphic type constructions is expressed as follows:

++++
<!-- 🐖
triple -> |inst?lst[int,int,int]<=int{3}(){>-[,]}
{1,2,3,4,5,6}.triple()
-->
++++

[NOTE]
====
The `triple` instruction code is composed of a single instruction: `>-[,]`. This syntactic sugar resolves `merge([,])`. The instruction signature of `merge` is  `A\<=#{+*+}(A::T)`. This states that `merge` is a **barrier instruction** that maps the entire lhs stream of objs (`#{+*+}`) to a single `A`, where `A` is a generic bound to `lst` given the resolution of the argument `A::T`. Thus, this instance of `merge` yields a single `lst` whose elements are the instructions three (`int{3}`) incoming lhs objs.  
====

An instruction is evaluated by applying a left-hand side `obj` as follows:

++++
<!-- 🐖
sum -> reduce?int<=int{*}(){fold(0,plus(_))}
-->
++++


An instruction is evaluated by applying a left-hand side `obj` as follows:

[source,mtron]
----
lhs => ?dom        [-- verify the lhs obj in the inst domain --]
=> arg0        [--  ┐                                    --]
=> ...         [--  ├── resolve arguments by applying the lhs to each
=> argN        [--  ┘                                    --]
=> code        [-- apply the lhs the first inst of the code block with args accessible on the stack --]
=> rhs         [-- the out of the code block is the result of the instruction --]
rhs => ?rng [-- verify the result is in the inst range --]
----


\begin{align*}
\texttt{inst} \in (\underbrace{\texttt{obj}}_{\text{the lhs object}} \times \underbrace{\texttt{inst}}_{\text{the instruction}}) \rightarrow \underbrace{\texttt{obj}}_{\text{the rhs object}}
\end{align*}


An instruction set is defined as a **record** (`rec`) of the form:

[source,mtron]
----
instset -> rec::T[?[type  => T{*}::T,                        [-- type definitions                   --]
inst  => inst{*}::T,                     [-- instruction definitions            --]
const => #::T,                           [-- constant definitions:              --]
sugar => rec::T[?[str::T=>uri::T]]]]     [-- syntactic sugar: token to inst tid --]
----


\begin{align*}
\texttt{inst} \in (\underbrace{\texttt{obj}}_{\text{the lhs object}} \times \underbrace{\texttt{inst}}_{\text{the instruction}}) \rightarrow \underbrace{\texttt{obj}}_{\text{the rhs object}}
\end{align*}


that is used to write programs that form an a

for composing data flow instructions.
The language draws inspiration from the referential constructs of C, the data selection and push-down predicates of SQL, the structural typing of TypeScript, the tersenes of form and underlying navigation perspective realized in Gremlin, the self-reflective URI addressable scheme of NenoFhat and RDF/OWL, and the record-oriented foundation of JavaScript.

[source,mtron]
----
*milky_way>>bodies.?star::T.where(>>planets.count().?>(0)).-<[
name            => >>name,
stats           => -<[kilos => >>mass.as(kg::T),
area  => _(s=>?star::T){ *pi.mult(*s.>>radius.pow(2.0)).as(km::T) }],
primary_planets => >>planets.order(>>mass).take(1).>>name]
----

Instructions, like the data it operates on, exist within the URI address space so that meta-programming concepts such as reflection, memoization, and serialization of the computational state can be naturally expressed and leveraged.

An instruction set packages types, constants, instructions, and syntax sugars and can be imported and used to effect domain-specific views the underlying data.