[discrete]
== Large Language Models

Modern AI techniques are heavily leveraged across various aspects of metatron, with popular cloud service providers (e.g. link:https://www.anthropic.com/[Anthropic] and/or link:https://openai.com/[OpenAI]) and local providers (e.g. link:https://ollama.com/[Ollama]) serving as the compute-intensive inferencing backends.

. **Pair Programmer**: LLMs can connect to a console session, be provided a terminal split screen, and evaluate mtron expressions alongside the user. This is especially useful when developing strategies for interlinking spaces via schema alignment and entity resolution as well as quickly creating domain-specific rewrite rules to optimize mtron compilation (using mtron).
. **Agent Development**: A large portion of an LLM's functional elements are embedded in the URI address space and made accessible to mtron via respective spaces. Such components include:
 - **tools**: every mtron `inst` has an `as()`-mapping to `tool`, where the `docq` q processor of the `inst` provides the name, description, and argument notes necessary for LLM tool selection. While most mtron instructions are low-level and not necessarily "tool-oriented", user-defined custom instruction can be as tool/service oriented as needed.
 - **thoughts**: when enabling internal reasoning with a supporting LLM, the stream of thought is published streamed and can be directed to system output, to a memory structure, to another LLM for review, etc.  
 - **memory**: an LLMs interaction/thought history can be stored and retrieved at a later time to enable long-term memory and context awareness.
 - **skills**: an LLM can be trained on a wide range of skills and domains, allowing them to perform complex tasks and solve problems. Skills can be pulled from the Anthropic-designed `.agent` directory that has a corresponding `SKILL.md` file and associated resources. Or, can be created programmatically in metaron.
 - **prompts**: specific prompts or instructions can be stored and retrieved to help guide an LLM's response.
 - **response formats**: a mtron `rec` can serve as a schema object instructing the LLM to populate the `rec` with their answer to avoid arbitrary string responses in favor of structured responses.
 - **gguff vector files**: ...
. **MCP Servers**: Developing and deploying MCP servers in mtron as well as interacting with remote MCP servers as a client is straightforward. Such simplicity provides a countless number of ways in which LLMs can interact with the underlying spaces.

[discrete]
=== LLM Space Embedding

An LLM is a `rec` with the following type definition:

++++
<!-- 🐖
*/m/llm/model
-->
++++

++++
<!-- 🐖
*ollama:+
-->
++++

[discrete]
=== LLM Interactions

The following example demonstrates how to search for an appropriate LLM for the given task, then query it, and finally, have its memory of the interaction stored in space for future use as a stabilizing content.

++++
<!-- 🐖 [SKIP]
ai -> *ollama:+                            /
      .where([skill=>has(thinking),
              size =>is(and(gt(mB::1000.0),lt(mB::5000.0)))]) /
       .order(>>size.mult(-1.0))    /
       .take(1)
*ai>>=[think=>true,
       memory=>/usr/ai/memory,
       tools =>!*eval]
*ai.+[think=>print(_),response=>to(/usr/ai/response)]
   .chat("Remember the word 'metatron'. I'll ask you to recall this word later.")
-->
++++

[NOTE]
--
The `size` relation maps to a `gB::T` (gigabytes) while the `where()` clause filtered on `mB::T` (megabytes). The conversion between the various data size units is handled automatically by the type constructors of the various data type sizes distributed in the `/m/math` instruction set.
--

[source,mtron]
----
*/m/math/+/
----

++++
<!-- 🐖
gB::500.0.as(mB::T)
-->
++++

The content and metadata associated with the chat interaction is stored at the specified location and is accessible via a `uri` dereference.

++++
<!-- 🐖
*/usr/mem
-->
++++

The memory is referenced again below, where it is both read (the previous interaction) and written to (the current interaction).

++++
<!-- 🐖 [SKIP]
*ollama:+                                  /
  .where([think=>true,size=>?<mB::5000.0]) /
  .order(>>?real<=rec(size).mult(-1.0))    /
  .take(1)                                 /
  .plus?rec<=rec([memory=>/usr/mem])       /
  .chat("What was the special word I needed you to recall?")
-->
++++

[discrete]
=== LLM Tools, Skills, and MCP Servers

++++
<!-- 🐖
[,]@/usr/ai/memory                                             [-- <1>
*openai:gpt-4o-2024-11-20 +   /
   [think=>print(_),          /
    response=>[to=>print(_)]].to(agent)                        [-- <2>
<openai:gpt-4o-2024-08-06/skill>                    /
  ->(*<local:software/metatron/.agent/skills/mtron> / 
      .as(skill::T).>-[,])                                     [-- <3>
<openai:gpt-4o-2024-08-06/tool> ->([!*eval])                   [-- <4>
<openai:gpt-4o-2024-08-06/memory> ->(|!*/usr/ai/memory)        [-- <5>
*<openai:gpt-4o-2024-08-06>                                    [-- <6>
*<openai:gpt-4o-2024-08-06>.>>=[_=>^*]                         [-- <7>
agent -> *<openai:gpt-4o-2024-08-06>                           [-- <8>
-->
++++
<1> an address to store agent memory
<2> a rudimentary chat-oriented agent.
<3> giving the agent the mtron `eval` instruction as a tool.
<4> giving the agent the mtron `mtron` skill (`SKILL.md`).
<5> linking the agent's memory to the specified address.
<6> an stateful, computationally enriched agent.
<7> compressing the agent `model::T` by using `!*` references.
<8> a stack-patterned uri referencing enriched llm created for convenience

++++
<!-- 🐖 
*agent.chat('what tools do you have access to?',          /
            [number_of_tools=>int::T,tool_names=>str::T])      [-- <1>
*agent.chat('what skills do you have?')                        [-- <2>
*agent>>memory                                                 [-- <3>
*agent>>memory/2/attributes/format                             [-- <4>
-->
++++
<1> providing a response format `rec` yields a structured response.
<2> without a response format, the agent replies in free, unstructured text.
<3> the agent's memory records structured responses.


[discrete]
=== Agent-Based Programming Language

The LLM, its memory, tools, skills, thoughts, and response formats are all first class entities in the metatron. Interacting
with an LLM is equivalent to evaluating an instruction. Moreover, an LLM's response is simply the `rhs` of
the instruction. As such, in mtron, function composition applies to LLM interactions. 
Agent-oriented computations can be defined and executed in a "workflow" type manner.
Conceptually, the LLM's state exists in (side effect/monadic) space, where instructions along the code's execution path 
can access it accordingly and naturally.

[source,mtron]
----
    enriched llm                                                  
   ┌──────────────────────────────────────────────────┐           
   │       memory                       thoughts      │           
   │       tools                        skills        │           
   │       response format                            │           
   └──────────────────────────────────────────────────┘           
                   .               .               .              
                   .               .               .              
                   .             ┌────┐            .              
                   .          ┌─►│chat├──────────┐ .              
                   .          │  └────┘          │ .              
                   .          │                  │ .              
                   .          │                  ▼ .              
   ┌────┐        ┌────┐       │  ┌────┐         ┌────┐            
---│    ├───────►│chat├───────┼─►│    ├────────►│chat│---        
   └────┘        └────┘       │  └────┘         └────┘            
                              │                  ▲                
                              │                  │                
                              │  ┌────┐          │                
                              └─►│    ├──────────┘                
                                 └────┘                           
----

The mtron example below contains two structured response calls to the agent used in the running examples thus far. Note the use of the tools provided to
the agent.

++++
<!-- 🐖
*agent                                                                          [-- <1>
*agent.chat('what is 6 + 23?',[answer=>int::T])                                 /
       .where([answer => ?>20])                                                 /  
       .*agent.chat('what was the last answer you gave me?',[answer=>int::T])   /
       .>>answer                                                                /
       .-<|[?>23 => print('a big answer'),                                      /
               _ => print('a small answer')].>>.mult(1000)                      [-- <2>
*/usr/ai/memory                                                                 [-- <3>
-->
++++

<1> The agent used in the previous examples.
<2> Treat `chat()` like any other instruction within a larger mtron composition.
<3> The llm's memory structure with requests and responses accessible.