[discrete]
== Large Language Models

Large language models (LLM) can be embedded in space. An LLM is a `rec` with the following type definition:

++++
<!-- 🐖
*/m/llm/model
-->
++++

++++
<!-- 🐖
*ollama:+
-->
++++


The following example demonstrates how to search for an appropriate LLM for the given task, then query it, and finally, have its memory of the interaction stored in space for future use as a stabilizing content.

++++
<!-- 🐖 [SKIP]
ai -> *ollama:+                            /
       .where([think=>true,size=>?<mB::5000.0]) /
       .order(>>?real<=rec(size).mult(-1.0))    /
       .take(1)
ai/think  -> false
ai/memory -> /usr/mem
*ai.chat("Remember the word 'metatron'. I'll ask you to recall this word later.")
-->
++++

[NOTE]
--
The `size` relation maps to a `gB::T` (gigabytes) while the `where()` clause filtered on `mB::T` (megabytes). The conversion between the various data size units is handled automatically by the type constructors of the various data type sizes distributed in the `/m/math` instruction set.
--

[source,mtron]
----
*/m/math/+/
----

++++
<!-- 🐖
gB::500.0.as(mB::T)
-->
++++
====

The content and metadata associated with the chat interaction is stored at the specified location and is accessible via a `uri` dereference.

++++
<!-- 🐖
*/usr/mem
-->
++++

The memory is referenced again below, where it is both read (the previous interaction) and written to (the current interaction).

++++
<!-- 🐖 [SKIP]
*ollama:+                                  /
  .where([think=>true,size=>?<mB::5000.0]) /
  .order(>>?real<=rec(size).mult(-1.0))    /
  .take(1)                                 /
  .plus?rec<=rec([memory=>/usr/mem])       /
  .chat("What was the special word I needed you to recall?")
-->
++++