[discrete]
== Large Language Models

Modern AI techniques are heavily leveraged across various aspects of metatron, with popular cloud service providers (e.g. link:https://www.anthropic.com/[Anthropic] and/or link:https://openai.com/[OpenAI]) and local providers (e.g. link:https://ollama.com/[Ollama]/http://localai.io[LocalAI]) serving as the compute-intensive inferencing backends.

. **Pair Programmer**: LLMs can connect to a console session, be provided a terminal split screen, and evaluate mtron expressions alongside the user. This is especially useful when developing strategies for interlinking spaces via schema alignment and entity resolution as well as quickly creating domain-specific rewrite rules to optimize mtron compilation (using mtron).
. **Agent Development**: A large portion of an LLM's functional elements are embedded in the URI address space and made accessible to mtron via respective spaces. Such components include:
 - **tools**: every mtron `inst` has an `as()`-mapping to `tool`, where the `docq` q processor of the `inst` provides the name, description, and argument notes necessary for LLM tool selection. While most mtron instructions are low-level and not necessarily "tool-oriented," user-defined custom instructions can be defined and offered as tools/services to llms as needed.
 - **thoughts**: when enabling internal reasoning with a supporting LLM, the stream of thought is published streamed and can be directed to system output, to a memory structure, to another LLM for review, etc.  
 - **memory**: an LLMs interaction/thought history can be stored and retrieved at a later time to enable long-term memory and context awareness.
 - **skills**: an LLM can be trained on a wide range of skills and domains, allowing them to perform complex tasks and solve domain-specific problems. Skills can be pulled from the Anthropic-designed `.agent` directory that has a corresponding `SKILL.md` file and associated resources. Or, can be created programmatically in metaron.
 - **prompts**: specific prompts or instructions can be stored and retrieved to help guide an LLM's response.
 - **response formats**: a mtron `rec` can serve as a schema object instructing the LLM to populate the `rec` with their answer to avoid arbitrary string responses in favor of structured responses.
 - **gguff vector files**: ...
. **MCP Servers**: Developing and deploying MCP servers in mtron as well as interacting with remote MCP servers as a client is straightforward. Such simplicity provides a countless number of ways in which LLMs can interact with the underlying spaces.

[discrete]
=== llm space embedding

An LLM is a `model::T < rec::T` with the following type definition:

++++
<!-- 🐖
*/m/llm/model
-->
++++

++++
<!-- 🐖
*ollama:+.take(3)
-->
++++

[discrete]
=== llm interactions

The following example demonstrates how to search for an appropriate LLM for the given task, then query it, and finally, have its memory of the interaction stored in space for future use (to provide the agent context over longer interactions).

++++
<!-- 
ai -> *ollama:+/+                                             /
      .where([skill=>has(thinking),                           /
              size =>is(and(gt(mB::1000.0),lt(mB::5000.0)))]) /
       .order(>>size.mult(-1.0))                              /
       .take(1)                                               
*ai>>=[think=>true,                                           /
       memory=>[mem=>/usr/mem,max=>5],                        /
       tools =>!*eval]
*ai.+[think=>print(_),response=>to(/usr/ai/response)]  
   .chat("Remember the word 'metatron'. I'll ask you to recall this word later.")
*/usr/ai/response
-->
++++

[.card]
--
[discrete,.center]
==== a note on unit conversions
The `size` relation maps to a `gB::T` (gigabytes) while the `where()` clause filtered on `mB::T` (megabytes). The conversion between the different data size units is handled automatically by the type constructors of those data size types. These types are distributed in the `/m/math` instruction set and imported via `import(/m/math)` (or `import(/m/math,math:)` if naming conflicts may emerge).

++++
<!-- 🐖
*/m/math.>>type.>>    [-- <1>
-->
++++
<1> get the types defined in `/m/math` `instset` and then drain that `lst` to a stream to see a more detailed string representation. 

++++
<!-- 🐖
gB::500.0.as(mB::T)    [-- <1>
gB::500.0.as(kB::T)    [-- <2>
tB::1.0.as(mB::T)      [-- <3>
-->
++++
<1> convert gigabytes to megabytes
<2> convert gigabytes to kilobytes
<3> convert terabytes to megabytes
--

The content and metadata associated with the chat interaction are stored at the specified location, where it is both read (the previous interaction) and written to (the current interaction).

++++
<!-- 
*ollama:+/+                                  /
 .where([skill=>has(thinking),size=>?<mB::5000.0])  /
 .order(>>?real<=rec(size).mult(-1.0))     /
 .take(1)                                  /
 .plus?rec<=rec(                           /
  [memory=>[                               /
      mem=>/usr/mem,                       /
      max=>5]])                            /
  .chat("What was the special word I needed you to recall?")
-->
++++

[discrete]
=== llm tools, skills, and mcp servers

++++
<!-- 🐖
*<openai:gpt-4o>.at(robotron).                                   /  [-- <1>   
 side([,].at(<local:.agent/robotron/memory>)).                   /  [-- <2>
 >>=[think=>print(_),                                            /  [-- <3>
     tool=>[!*eval],                                             /  [-- <4>
     skill=>[                                                    /  [-- <5>
  !*<local:.agent/skills/mtron>.as(skill::T)],                   / 
     response=>[to=>print(_)],                                   /  [-- <6>
     memory=>[mem=>!*<local:.agent/robotron/memory>,max=>20]].   /  [-- <7>
 >>=[_=>^*_]                                                        [-- <8>
-->
++++
<1> clone the base model to the `robotron` address
<2> as a side-effect, create a blank memory structure and store it on the local file system
<3> print robotron's thoughts to the terminal
<4> give robotron access to the `eval?A\<=#{?}(str::T)` instruction for evaluating mtron expressions
<5> give robotron the `mtron` skill set (`SKILL.md` file in `.agent/skills/mtron` directory)
<6> print roboton's response to the terminal
<7> pass robotron a reference to the memory structure and cap its growth to 15 entries.
<8> re-reference any resolved `!\*` (`auto_from`) references using `^*` (`auto_to`).

++++
<!-- 🐖 
*robotron.chat('what tools do you have access to?',          /
            [number_of_tools=>int::T,tool_names=>str::T])         [-- <1>
*robotron.chat('what skills do you have?')                        [-- <2>
*robotron>>memory                                                 [-- <3>
*robotron>>memory/mem/2/attributes/format                         [-- <4>
-->
++++
<1> providing a response format `rec` yields a structured response.
<2> without a response format, the agent replies in free, unstructured text.
<3> the agent's memory records structured responses.


[discrete]
=== agent-based programming language

The LLM, its memory, tools, skills, thoughts, and response formats are all first-class entities in the metatron. Interacting
with an LLM is equivalent to evaluating an instruction. Moreover, an LLM's response is simply the `rhs` of
the instruction. As such, in mtron, function composition applies to LLM interactions. 
Agent-oriented computations can be defined and executed in a "workflow" type manner.
Conceptually, the LLM's state exists in (side effect/monadic) space, where instructions along the code's execution path 
can access it accordingly and naturally.

[source,mtron]
----
    enriched llm                                                  
   ┌──────────────────────────────────────────────────┐           
   │       memory                       thoughts      │           
   │       tools                        skills        │           
   │       response format                            │           
   └──────────────────────────────────────────────────┘           
                   .               .               .              
                   .               .               .              
                   .             ┌────┐            .              
                   .          ┌─►│chat├──────────┐ .              
                   .          │  └────┘          │ .              
                   .          │                  │ .              
                   .          │                  ▼ .              
   ┌────┐        ┌────┐       │  ┌────┐         ┌────┐            
---│    ├───────►│chat├───────┼─►│    ├────────►│chat│---        
   └────┘        └────┘       │  └────┘         └────┘            
                              │                  ▲                
                              │                  │                
                              │  ┌────┐          │                
                              └─►│    ├──────────┘                
                                 └────┘                           
----

The mtron example below contains two structured response calls to the agent used in the running examples thus far. Note the use of the tools provided to the agent.

++++
<!-- 🐖
*robotron                                                                          [-- <1>
*robotron.chat('what is 6 + 23?',[answer=>int::T])                                 /
       .where([answer => ?>20])                                                    /  
       .*robotron.chat('what was the last answer you gave me?',[answer=>int::T])   /
       .>>answer                                                                   /
       .-<|[?>23 => print('a big answer'),                                         /
               _ => print('a small answer')].>>.mult(1000)                         [-- <2>
*<local:.agent/robotron/memory>                                                    [-- <3>
-->
++++

<1> The agent used in the previous examples.
<2> Treat `chat()` like any other instruction within a larger mtron composition.
<3> The llm's memory structure with requests and responses accessible.