[discrete]
== The Instruction

++++
<!--
┌ ├ ┐ └ ┘ │ ┤ ─ ⋰ ⋱ ⮝ ⮞ ⮜ ⮟
-->
++++

mtron programs are composed using computational primitives called **instructions** (`inst`). Instructions are organized into libraries called **instruction sets** (`instset`) -- domains of discourse. Mathematically, every instruction is a **function** written according to the form:

[source,mtron]
----
tid?rng<=dom(args){ code }@vid
│  │ │  │ │ │  │   │    │   │
│  └─┘  └─┘ └──┘   └────┘   │
│   │    │    │      │      └───⮞ location: instance location
│   │    │    │      └──────────⮞ code: a nested chain of instructions
│   │    │    └─────────────────⮞ arguments: dynamic parameterizations (rhs)
│   │    └──────────────────────⮞ domain: the incoming obj (lhs)
│   └───────────────────────────⮞ range: the outgoing obj (return)
└───────────────────────────────⮞ the id of the instruction
----

Every instruction maps a **left hand side** `obj` (`lhs`) to a **right hand side** `obj` (rhs). Many-to-one, one to many, and many-to-many mappings are possible as an `obj` is an element in the power set of all `objs`. Thus, `{1,2,3}` is an `obj` with type `int{3}`.

\begin{align*}
\text{obj} \in \mathcal{P}(\text{obj})
\end{align*}


[indent=0,subs="verbatim,attributes",role="primary"]
.positional args
=====

[stem]
++++
\tt{obj}_\tt{in}.f(\color{yellow}{\__{0}}, \color{yellow}{\__{1}},\ldots,\color{yellow}{\__{n}}) \mapsto \tt{obj}_\tt{out}
++++

An `inst` frame is defined by the `inst` https://en.wikipedia.org/wiki/Parameter_(computer_programming)[arguments].
These arguments can be accessed within the `inst` via their `lst` position as a fURI.
For example, `\*<0>` references the first argument, `*<1>` the second argument, so on and so forth.

++++
<!-- 🐖 
band -> |inst?int{?}<=int(int::T,int::T){ is(and(gte(*0),lte(*1))) }
3.band(2,8)                                [-- <1>
10.band(2,8)                               [-- <2>
-->
++++

<1> `3` is within the band `[2,8]` and thus, `3` is the result, satisfying the `inst` range `int{?}`.
<2> `10` is not within the band `[2,8]` and thus, `noobj` is the result, satisfying the `inst` range `int{?}`.
=====

[indent=0,subs="verbatim,attributes",role="secondary"]
.named args
=====

[stem]
++++
\tt{obj}_\tt{in}.f(\color{yellow}{a_1} \Rightarrow x, \color{yellow}{a_2} \Rightarrow y,\ldots,a_n) \mapsto \tt{obj}_\tt{out}
++++

A https://en.wikipedia.org/wiki/Named_parameter[named argument] is a fURI that references an `obj` in the router's frame structure.

++++
<!-- 🐖 
band -> |inst?int{?}<=int(min=>_,max=>_){ is(and(gte(*min),lte(*max))) }
3.band(2,8)                           [-- <1>
3.band(max=>8,min=>2)                 [-- <2>
'abc'.band(2,8)                       [-- <3>
-->
++++


<1> If the argument name isn't provided, then it's position in the argument list determines its nane,
<2> When arguments are named, they can be written in any order.
<3> The domain of `band` is `int`.
Note where the error is thrown when `str['abc']` is provided.
=====

[indent=0,subs="verbatim,attributes",role="secondary"]
.default args
=====

[stem]
++++
\tt{obj}_\tt{in}.f(a_1 \Rightarrow \color{yellow}{else(x)},a_2 \Rightarrow \color{yellow}{else(y)},\ldots,a_n) \mapsto \tt{obj}_\tt{out}
++++

If the incoming `obj` to `else` is `noobj`, the `else` emits it's argument, else it emits the incoming `obj`.
This makes `else` useful for expressing https://en.wikipedia.org/wiki/Default_argument[default arguments].

++++
<!-- 🐖 
band -> |inst?int{?}<=int(min=>else(2),max=>else(8)){ is(and(gte(*min),lte(*max))) }
1.band(min=>1)                        [-- <1>
10.band()                             [-- <2>
{2,3,4,5}.band(min=>3,max=>4)         [-- <3>
-->
++++

<1> No `max` is provided, so the default value of `8` is used.
<2> No `min` nor `max` is provided, so the defaults `2` and `8`, respectively are used.
<3> When arguments are provided, the default values are not used.
=====

[indent=0,subs="verbatim,attributes",role="secondary"]
.typed args
=====

[stem]
++++
\tt{obj}_\tt{in}.f(a_1\color{yellow}{?type_1}, a_2\color{yellow}{?type_2},\ldots,a_n) \mapsto \tt{obj}_\tt{out}
++++

If an argument is defined with a query https://en.wikipedia.org/wiki/Data_type[type], then the argument's value must satisfy that type's specification.
This is a consequence of attaching a type query processor to the router frame structure and thus, is analogous to type specifications in other structures.

++++
<!-- 🐖 
nat -> int::T[?>0]
band -> |inst?int{?}<=int(min=>?nat::T,max=>?nat::T){ is(and(gte(*min),lte(*max))) }
15.band(10,20)              [-- <1>
-15.band(-20,-10)           [-- <2>
-->
++++

<1> Argument name uniqueness does not consider query parameters.
<2> The `?nat` query parameter requires the respective argument be some stem:[n \in \mathbb{N}].
=====

[indent=0,subs="verbatim,attributes",role="secondary"]
.anonymous args
=====

[stem]
++++
\tt{obj}_\tt{in}.\color{yellow}{\lambda}(a_1 \Rightarrow x, a_2 \Rightarrow y,\ldots,a_n) \mapsto \tt{obj}_\tt{out}
++++

An untyped `inst` is an anonymous `inst` and behaves analogously to an
https://en.wikipedia.org/wiki/Anonymous_function[anonymous function] in other programming environments.
Anonymous `insts` can be both defined and evaluated in the same expression to provide
https://en.wikipedia.org/wiki/Immediately_invoked_function_expression[immediately invoked function expression] semantics.
Like any `inst`, anonymous `inst` arguments are scoped to the value of the `inst`, providing
https://en.wikipedia.org/wiki/Scope_(computer_science)#Block_scope[block-scope] semantics.
Finally, a degenerate anonymous `inst` with no specified variable frame is simply `bcode`.

++++
<!-- 🐖 
10.(min=>2,max=>8){ is(and(gte(*min),lte(*max))) }                [-- <1>
10.(min=>minus(1),max=>plus(1)){ is(and(gte(*min),lte(*max))) }   [-- <2>
10.(){ is(and(gte(*min),lte(*max))) }                             [-- <3>
10.is(and(gte(minus(1)),lte(plus(1))))                            [-- <5>
-->
++++

<1> The unnamed "band" `inst` is evaluated in line.
<2> `min` and `max` are computed dynamically relative to the input.
<3> The `inst` value is referencing undefined frame variables.
<4> An anonymous `inst` is compiled to an `obj` filter-`inst`.
<5> When arguments are embedded in the value, then the `inst` is simply `bcode`.
=====

[indent=0,subs="verbatim,attributes",role="secondary"]
.contextualargs
=====

++++
<!-- 🐖 
is_divisible -> |is_divisble?bool<=int(by?int=>_)[mod(*by).eq(0)]
10.is_divisible(2)
10.is_divisible('abc')
-->
++++
=====

[indent=0,subs="verbatim,attributes",role="secondary"]
.dependent args
=====

[stem]
++++
\tt{obj}_\tt{in}.f(a_1 \Rightarrow x,a_2 \Rightarrow \color{yellow}{g(*a_1)},\ldots,a_n) \mapsto \tt{obj}_\tt{out}
++++

If an argument's type is dependent on the value of another argument, then the argument is a https://en.m.wikipedia.org/wiki/Dependent_type[dependent argument].

++++
<!-- 🐖 
band -> |band?int{?}<=int(min=>_,max=>is(gt(*min)).else(*min.plus(1)))[is(gte(*min)).is(lte(*max))]
2.band(min=>1,max=>1)                 [-- <1>
-->
++++

<1> ...
=====

[indent=0,subs="verbatim,attributes",role="secondary"]
.refined args
=====

++++
<!-- 🐖 
is_divisible -> |is_divisble?bool<=int(by?int=>is(neq(0)).else(print('error').map(1)))[mod(*by).eq(0)]
10.is_divisible(2)
10.is_divisible('abc')
-->
++++
=====




An `inst` to create `int` triples can be written:

++++
<!-- 🐖
triple -> |inst?lst<=int{3}(){>-[,]}
{1,2,3,4,5,6}.triple()
-->
++++

[NOTE]
====
The `|` token is synatic sugar for the `block` inst. A blocked instruction prevents the application of the `lhs` to the `inst` args and `inst` code.
This ensures the uri `triple` is not applied to the `inst` prior to the uri being bound as the reference (`->`). Without block, the result of applying `triple` to `inst` would be what `triple` is bound to. In this particular instance, `triple` would reference a `fail` obj.

++++
<!-- 🐖
triple -> inst?lst[int,int,int]<=int{3}(){>-[,]}
*triple
-->
++++

====

A stricter representation leveraging polymorphic type constructions is expressed as follows:

++++
<!-- 🐖
triple -> |inst?lst[int,int,int]<=int{3}(){>-[,]}
{1,2,3,4,5,6}.triple()
-->
++++

[NOTE]
====
The `triple` instruction code is composed of a single instruction: `>-[,]`. This syntactic sugar resolves `merge([,])`. The instruction signature of `merge` is  `A\<=#{\*}(A::T)`. This states that `merge` is a **barrier instruction** that maps the entire lhs stream of objs (`#{*}`) to a single `A`, where `A` is a generic bound to `lst` given the resolution of the argument `A::T`. Thus, this instance of `merge` yields a single `lst` whose elements are the instructions three (`int{3}`) incoming lhs objs.  
====

An instruction is evaluated by applying a left-hand side `obj` as follows:

++++
<!-- 🐖
sum -> reduce?int<=int{*}(){fold(0,plus(_))}
-->
++++


An instruction is evaluated by applying a left-hand side `obj` as follows:

[source,mtron]
----
lhs => ?dom        [-- verify the lhs obj in the inst domain --]
=> arg0        [--  ┐                                    --]
=> ...         [--  ├── resolve arguments by applying the lhs to each
=> argN        [--  ┘                                    --]
=> code        [-- apply the lhs the first inst of the code block with args accessible on the stack --]
=> rhs         [-- the out of the code block is the result of the instruction --]
rhs => ?rng [-- verify the result is in the inst range --]
----


\begin{align*}
\texttt{inst} \in (\underbrace{\texttt{obj}}_{\text{the lhs object}} \times \underbrace{\texttt{inst}}_{\text{the instruction}}) \rightarrow \underbrace{\texttt{obj}}_{\text{the rhs object}}
\end{align*}


An instruction set is defined as a **record** (`rec`) of the form:

[source,mtron]
----
instset -> rec::T[?[type  => T{*}::T,                        [-- type definitions                   --]
inst  => inst{*}::T,                     [-- instruction definitions            --]
const => #::T,                           [-- constant definitions:              --]
sugar => rec::T[?[str::T=>uri::T]]]]     [-- syntactic sugar: token to inst tid --]
----


\begin{align*}
\texttt{inst} \in (\underbrace{\texttt{obj}}_{\text{the lhs object}} \times \underbrace{\texttt{inst}}_{\text{the instruction}}) \rightarrow \underbrace{\texttt{obj}}_{\text{the rhs object}}
\end{align*}


that is used to write programs that form an a

for composing data flow instructions.
The language draws inspiration from the referential constructs of C, the data selection and push-down predicates of SQL, the structural typing of TypeScript, the tersenes of form and underlying navigation perspective realized in Gremlin, the self-reflective URI addressable scheme of NenoFhat and RDF/OWL, and the record-oriented foundation of JavaScript.

[source,mtron]
----
*milky_way>>bodies.?star::T.where(>>planets.count().?>(0)).-<[
name            => >>name,
stats           => -<[kilos => >>mass.as(kg::T),
area  => _(s=>?star::T){ *pi.mult(*s.>>radius.pow(2.0)).as(km::T) }],
primary_planets => >>planets.order(>>mass).take(1).>>name]
----

Instructions, like the data it operates on, exist within the URI address space so that meta-programming concepts such as reflection, memoization, and serialization of the computational state can be naturally expressed and leveraged.

An instruction set packages types, constants, instructions, and syntax sugars and can be imported and used to effect domain-specific views the underlying data.