[discrete]
== Uniform Resource Identifiers

[source,mtron]
----
file://domain.local:22/usr/data/abc{*}?sub
  │    └──────────┘ │  └──────────┘ │  └────⮞ q(uery)
  │          │      │        │      └───────⮞ c(oefficient)   
  │          │      │        └──────────────⮞ path
  │          │      └───────────────────────⮞ port
  │          └──────────────────────────────⮞ host
  └─────────────────────────────────────────⮞ scheme
----

[cols="7a,5a",separator=🧱,role=noborder]
|===
🧱

metatron was designed to support the creation and manipulation of _abstract data types_ in a manner that affords the user a concise, fluid means of maneuvering through a heterogeneous set of data structures, where each is embedded within and across any number of spaces, while being respectfully agnostic to each space's espoused perspective on the data maintained therein: e.g., key/value, document, relational, vector, graph, file system, and the various peculiarities between.

metatron's URI addressing scheme makes it possible to encode arbitrary data types into a metatron-specific construct called "space". A space is where URI/obj pairs are written to and read from. Coupling occurs when a URI references an obj. The most basic form of read/write is to dereference/reference using the instructions `from` and `to` with signatures

[source,mtron]
----
from?B{*}<=A{?}(?uri::T)
to?A{?}<=A{?}(?uri::T)
----

and example usages

[source,mtron]
----
1.to(a) [-- write 1 to a  --]
from(a) [-- read 1 from a --]
----

along with their respective sugar forms:

[source,mtron]
----
a -> 1  [-- write 1 to a --]
*a      [-- read 1 from a --]
----

From `to` and `from` more complex read/write patterns are realized such `select` and `update` (discussed elsewhere in the Tractatus).


🧱
[source,mtron]
----
               ┌─────── a/b       
 ┌─────────────┼────────────── b       
 │     ┌───────┼─────────── a/b/c      
 │     │   ┌───┼─── http://localhost:8080                
 │   ┌─▼┐  │  ┌▼┐                           
┌▼─┐ │  │  │  └─┘                           
│  │ └──┘┌─▼┐    ┌──┐                       
└──┘  ┌─┐└──┘ ┌─┐│  ◄──────── a.local         
 ┌────►─┘     └▲┘└──┘                       
 │ ┌─┐ ┌─◄┐┌──┐│    ┌◄─────── xyz        
 │ └▲┘ └─┘││  ││    └┘                      
 │  │ ┌──┐│└─▲┘└─────── mtron:ab            
 │  │ │  ││  └───────────── z        
 │  │ └─▲┘└────────────────── /a/b        
 │  │   └────────────── xx:host.com/abc        
 │  └───────────────────────── yy       
 └────────────────────── xx     
----

|===

Any obj can be referenced by a URI. From simple **mono** objs such as `bool`, `int`, etc. to complex nested **poly** objs such as `rec`, `lst`, etc. Poly objs provide another layer of addressing in that once a poly obj has a URI reference, the internal objs that make up the poly inherit that reference and extend it with any internal references necessary to find the objs within the poly.

[cols="8a,6a",separator=🧱]
|===
🧱
[source,mtron]
----
a/b/c -> [x,[y=>[z=>2]]]
         ▲▲ ▲   ▲   ▲  
         ││ │   │   └────── a/b/c/y/z     <5>
         ││ │   └────────── a/b/c/1/y     <4>
         ││ └────────────── a/b/c/1       <3>
         │└──────────────── a/b/c/0       <2>
         └───────────────── a/b/c         <1>
----

[mtron]
----
a/b/c -> [x,[y=>[z=>2]]]   
*a/b/c                     [-- <1> --]
*a/b/c/0                   [-- <2> --]
*a/b/c/1                   [-- <3> --]
*a/b/c/1/y                 [-- <4> --]
*a/b/c/1/y/z               [-- <5> --]
----

🧱
<1> the uri `a/b/c` references a `lst` poly.
<2> the uri `a/b/c/0` references an internal `uri` mono.
<3> the uri `a/b/c/1` references an internal `rec` poly.
<4> the uri `a/b/c/1/y` references another internal `rec` poly.
<5> the uri `a/b/c/1/y/z` references an doubly internal `int` mono.
|===


[discrete]
=== Spatial Embeddings

[discrete]
==== The Poly Read/Write SubRing

When a poly containing nested poly structures is written to space an ambiguity emerges. A example will elucidate this point. Assume the two ways in which to encode "the same" data in space.

[cols="6a,8a"]
|===
|

[cols="3a,3a",option="header"]
!===
^!
**form A**
^!
**form B**
!
[mtron,source]
----
a->[b=>1,c=>2] 
----
!
[mtron,source]
----
a->[b=>1,c=>2]
----
!
[mtron,source]
----
     ┌──b──⮞1
   a─┤
     └──c──⮞2
----
!
[mtron,source]
----
    a──b──⮞1

    a──c──⮞2  
----
!===
<1> the uri ring defines multiplcation as "extension", where latexmath:[x \cdot y] is `x/y`.
<2> the uri ring defines addition as "branching", where latexmath:[x + y] is `{x,y}`. 

|
The two examples represent the equivalent data because there exists a bijection that maps **A** to **B** and **B** to **A**. In other words, they are isomorphic structures within the category of ring. The form **A** is captured by the equation:

\[
a \cdot (b + c) = \{1,2\}
\]

Form **B** has the equation:

\[
(a \cdot b) + (a \cdot c) = \{1,2\}
\]

Thus, due to the ring axiom that states multiplication distributes over addition, the two equations, while typographically different, are, in fact, algebraically equivalent.

\[
\begin{align*}
a \cdot (b + c)           &=&         \\
(a \cdot b) + (a \cdot c) &= ab + ac \\
\end{align*}
\]

|
[cols="3a,3a",option="header"]
!===
^!
**form A**
^!
**form B**
!
[mtron,source]
----
    *a/
----
!
[mtron,source]
----
    *a/b/
    *a/c/
----
!
[mtron,source]
----
a=>[b=1,c=>2]
----
!
[mtron,source]
----
{a/b=>1,a/c=>2}
----
!===
|
The inverse holds as well. That is, when reading from space, `*a/` and *a/b 
The two examples are "equal" because they can be rewritten into each using the ring algebra. The first form is the equation:

\[
a \cdot (b + c)
\]

The second is written:

\[
(a + b) \cdot (a + c)
\]

Thus, due to the fact that multiplication distributes over addition, the two equations, while typographically different are in fact the same data.

\[
a \cdot (b + c) = (a + b) \cdot (a + c)
\]

|===

If the implication of these equalities is not readily apparent, then understand the following. The multiplicative union of uris to an obj is a **dependent relationship**. There exists a colocational requirement where `a` is coupling `b` and `c` together into a single structure that then refers to `1` and `2`.

[mtron,source]
----
     ┌──b──⮞1
   a─┤
     └──c──⮞2
----

On the other hand, the additive union of the uris is an **independent relationship**. There are two representations of `a` and thus, `a/b \=> 1` is distinct, requiring no colocation with `a/c \=> 2`. This means that `a/b` can be stored in a document database in Japan and `a/c` an be stored in `.txt` file on some file system in Ohio and when resolved, the same `{1,2}` result is returned upon query (albeit with different time/space characteristics compared to the multiplicative, colocated representation of the data).

[mtron,source]
----
    a──b──⮞1

    a──c──⮞2  
----


A further entailment states that a dataset can be rewritten from a **concatenative/multiplicative** form to a **union/additive** form so as to maintain one subset of the data in a specialized space optimized for the demands of its production requirements and the other subset in some other specialized space according to its requirements. More specifically, some data needs to be "hot in cache" in order to satisfy demand, and some data should be "iced in archive" when the production usage doesn't require rapid response times and its possible to reduce production costs with cheap disk storage. With metatron, expressing such partitions while also ensuring said partitions resolve correctly is built into the fundamental mathematics/algorithm of the system -- **the ring algebra for structural composition**.  

[discrete]
==== Isomorphic != Identical

A _matrix_ is an latexmath:[n \times m] data structure composed of latexmath:[n] vectors/row, each with latexmath:[m] elements/columns. A relational database _table_ is an example of a matrix, where the entries typically span numeric and non-numeric data types. Three general approaches to embedding a matrix or table into a space are presented below, where each makes different space/time tradeoffs, while remaining isomorphic with respect to the structural ring algebra.

[cols="5,5,5",frame=none,subs="+macros",separator=🧱,grid=cols, role="center"]
|===

^a🧱

[.big]
[source,mtron]
----
 \    |   |    /
 [■] [■] [■] [■]

-[■] [■] [■] [■]-

 [■] [■] [■] [■]
 /    |   |    \

----

^a🧱

[.big]
[source,mtron]
----
​
[■]-[■]-[■]-[■]

[■]-[■]-[■]-[■]

[■]-[■]-[■]-[■]
​
----

^a🧱

[.big]
[source,mtron]
----
​
[■]-[■]-[■]-[■]
 |   |   |   |
[■]-[■]-[■]-[■]
 |   |   |   |
[■]-[■]-[■]-[■]
​
----

a🧱

[mtron]
----
m/0/0 -> 0
m/0/1 -> 1
m/0/2 -> 2
m/0/3 -> 3
m/1/0 -> 4
m/1/1 -> 5
m/1/2 -> 6
m/1/3 -> 7
m/2/0 -> 8
m/2/1 -> 9
m/2/2 -> 10
m/2/3 -> 11
*m/0/0       [-- <1> --]
*m/0/+       [-- <2> --]
*m/+/0       [-- <3> --]
----

a🧱

[mtron]
----
m/0 -> [0,1,2,3]
m/1 -> [4,5,6,7]
m/2 -> [8,9,10,11]

*m/0/0       [-- <1> --]
*m/0/+       [-- <2> --]
*m/+/0       [-- <3> --]
----

a🧱

[mtron]
----
m -> [[0,1,2,3],  /
      [4,5,6,7],  /
      [8,9,10,11]]

*m/0/0       [-- <1> --]
*m/0/+       [-- <2> --]
*m/+/0       [-- <3> --]
----

|===

<1> Retrieve the first element of matrix `m`.
<2> Retrieve the first row of matrix `m`.
<3> Retrieve the first column of matrix `m`.

The above example demonstrates the power of structural embeddings.
The platonic matrix latexmath:[m] was embedded in a space using 3 different representations: _entry-wise_, _row-wise_, and _row-column wise_.
Next, each embedding was read: an _element read_, a _row read_ and a _column read_.
The expression used to read from each of the three embeddings is the same (typographically verbatim) and so is the result (algebraically isomorphic).
This is possible because a structure resolves up the fURI path hierarchy until it finds a match.
Once found, it then traverses within the match to resolve the remaining path segments.

.Amortized Costs in Terms of Time
[%header,width=70%,cols="l2,c1,c1,c1",role="small center"]
|===
| [.red]#embedding#              | [.red]#single-element#| [.red]#row-access#  | [.red]#column-access#
| [.red]#entry#          | \[O(1)\]       | \[O(n)\]    | \[O(m)\]
| [.red]#row#            | \[O(m)\]       | \[O(1)\]    | \[O(m)\]
| [.red]#row_column#     | \[O(1)\]       | \[O(1)\]    | \[O(1)\]
|===

The different embeddings also have different space costs, where space is defined as the amount of data accessed (i.e. retrieved from the structure) in order to satisfy the resolution of the respective fURI.

.Amortized Costs in Terms of Space
[.center]
[%header,width=70%,cols="l2,c1,c1,c1",role="small center"]
|===
| [.red]#embedding#              | [.red]#single-element# | [.red]#row-access#    | [.red]#column-access#
| [.red]#entry#          | \[O(1)\]       | \[O(n)\]      | \[O(m)\]
| [.red]#row#            | \[O(n)\]       | \[O(n)\]      | \[O(n+m)\]
| [.red]#row_column#     | \[O(n+m)\]     | \[O(n+m)\]    | \[O(n+m)\]
|===

[discrete]
=== Coefficients

[cols="3a,3a,3",separator=🧱,options=header,role="table-bordered small center"]
|===
🧱 [.red]#coefficient# 🧱 [.red]#shorthand# 🧱 [.red]#name#
🧱 {0,0}       🧱 {0}       🧱 noobj
🧱 {1,1}       🧱 {1} or    🧱 an-obj
🧱 {-1,-1}     🧱 {-1}      🧱 anti-obj
🧱 {±n,±n}     🧱 {±n}      🧱 exactly ±n
🧱 {±n,±m}     🧱           🧱  between ±n and ±m

🧱 {0,1}       🧱 {?}      🧱 maybe
🧱 {1,}        🧱 {+}      🧱 some
🧱 {0,}        🧱 {*}      🧱 maybe some

🧱 {-,+}       🧱 {**}     🧱 polar maybe some
🧱 {-1,1}      🧱 {??}     🧱 polar maybe

🧱 {-1,0}      🧱 {-?}     🧱 anti-maybe
🧱 {,-1}       🧱 {-}      🧱 anti-some
🧱 {,0}        🧱 {-*}     🧱 anti-maybe some
|===