[discrete]
== Uniform Resource Identifiers

[source,mtron]
----
file://domain.local:22/usr/data/abc{*}?sub
  │    └──────────┘ │  └──────────┘ │  └────⮞ q(uery)
  │          │      │        │      └───────⮞ c(oefficient)   
  │          │      │        └──────────────⮞ path
  │          │      └───────────────────────⮞ port
  │          └──────────────────────────────⮞ host
  └─────────────────────────────────────────⮞ scheme
----

[cols="7a,5a",separator=🧱,role=noborder]
|===
🧱

metatron was designed to support the creation and manipulation of _abstract data types_ in a manner that affords the user a concise, fluid means of maneuvering through a heterogeneous set of data structures, where each is embedded within and across any number of spaces, while being respectfully agnostic to each space's espoused perspective on the data maintained therein: e.g., key/value, document, relational, vector, graph, file system, and the various nooks and crannies between.

metatron's URI addressing scheme makes it possible to encode arbitrary data types into a metatron-specific construct called "space". A space is where URI/obj pairs are written to and read from. Coupling occurs when a URI references an obj.

[source,mtron]
----
1.to(a) [-- write 1 to a  --]
from(a) [-- read 1 from a --]

[== sugar form ==]
a -> 1  [-- write 1 to a --]
*a      [-- read 1 from a --]
----

🧱
[source,mtron]
----
               ┌─────── a/b       
 ┌─────────────┼────────────── b       
 │     ┌───────┼─────────── a/b/c      
 │     │   ┌───┼─── http://localhost:8080                
 │   ┌─▼┐  │  ┌▼┐                           
┌▼─┐ │  │  │  └─┘                           
│  │ └──┘┌─▼┐    ┌──┐                       
└──┘  ┌─┐└──┘ ┌─┐│  ◄──────── a.local         
 ┌────►─┘     └▲┘└──┘                       
 │ ┌─┐ ┌─◄┐┌──┐│    ┌◄─────── xyz        
 │ └▲┘ └─┘││  ││    └┘                      
 │  │ ┌──┐│└─▲┘└─────── mtron:ab            
 │  │ │  ││  └───────────── z        
 │  │ └─▲┘└────────────────── /a/b        
 │  │   └────────────── xx:host.com/abc        
 │  └───────────────────────── yy       
 └────────────────────── xx     
----

|===

Any obj can be referenced by a URI. From simple **mono** objs such as `bool`, `int`, etc. to complex nested **poly** objs such as `rec`, `lst`, etc. Poly objs provide another layer of addressing in that once a poly obj has a URI reference, the internal objs that make up the poly inherit that reference and extend it with any internal references necessary to find the objs within the poly.

[source,mtron]
----
a/b/c -> [x,[y=>[z=>2]]]
         ▲▲ ▲   ▲   ▲  
         ││ │   │   └────── a/b/c/y/z
         ││ │   └────────── a/b/c/1/y
         ││ └────────────── a/b/c/1
         │└──────────────── a/b/c/0
         └───────────────── a/b/c
----


++++
<!-- 🐖
a/b/c -> [x,[y=>[z=>2]]]
*a/b/c
*a/b/c/0
*a/b/c/1
*a/b/c/1/y
*a/b/c/1/y/z
-->
++++
<1> the uri `a/b/c` references a `lst` poly.
<2> the uri `a/b/c/0` references an internal `uri` mono.
<3> the uri `a/b/c/1` references an internal `rec` poly.
<4> the uri `a/b/c/1/y` references another internal `rec` poly.
<5> the uri `a/b/c/1/y/z` references an doubly internal `int` mono.

In summary, metatron's global, distributed memory system can be understood as a bag of binary relations mapping URIs to objs.

[.center]
[stem]
++++
\tt{SPACE} \in \left(\tt{URI} \times \tt{OBJ}\right)
++++

[discrete]
=== spatial embeddings

The following considerations apply when performing

. **spatial encodings**
. **schema encodings**
. **language encodings**

A _matrix_ is an \$n \times m\$ data structure composed of \$n\$ vectors/row, each with \$m\$ elements/columns. A relational database _table_ is an example of a matrix, where the entries typically span numeric and non-numeric data types.
Three general approaches to embedding a matrix or table into a space are presented below, where each makes different space/time tradeoffs.

[cols="5,5,8",frame=none,subs="+macros",separator=🧱,grid=cols, role="center"]
|===

^a🧱

[.big]
[source,mtron]
----
 \    |   |    /
 [■] [■] [■] [■]

-[■] [■] [■] [■]-

 [■] [■] [■] [■]
 /    |   |    \

----

^a🧱

[.big]
[source,mtron]
----
​
[■]-[■]-[■]-[■]

[■]-[■]-[■]-[■]

[■]-[■]-[■]-[■]
​
----

^a🧱

[.big]
[source,mtron]
----
​
[■]-[■]-[■]-[■]
 |   |   |   |
[■]-[■]-[■]-[■]
 |   |   |   |
[■]-[■]-[■]-[■]
​
----

a🧱

++++
<!-- 🐖
[-- write matrix --]
m/0/0 -> 0
m/0/1 -> 1
m/0/2 -> 2
m/0/3 -> 3
m/1/0 -> 4
m/1/1 -> 5
m/1/2 -> 6
m/1/3 -> 7
m/2/0 -> 8
m/2/1 -> 9
m/2/2 -> 10
m/2/3 -> 11
[-- read matrix --]
*m/0/0       [-- <1>
*m/0/+       [-- <2>
*m/+/0       [-- <3>
-->
++++

a🧱

++++
<!-- 🐖
[-- write matrix --]
m/0 -> [0,1,2,3]
m/1 -> [4,5,6,7]
m/2 -> [8,9,10,11]
[-- read matrix --]
*m/0/0       [-- <1>
*m/0/+       [-- <2>
*m/+/0       [-- <3>
-->
++++

a🧱

++++
<!-- 🐖
[-- write matrix --]
m -> [[0,1,2,3],[4,5,6,7],[8,9,10,11]]
[-- read matrix --]
*m/0/0       [-- <1>
*m/0/+       [-- <2>
*m/+/0       [-- <3>
-->
++++

|===

<1> Retrieve the first element of matrix `m`.
<2> Retrieve the first row of matrix `m`.
<3> Retrieve the first column of matrix `m`.

The above example demonstrates the power of structural embeddings.
The platonic matrix `m` was embedded in a structure using 3 different representations: _entry-wise_, _row-wise_, and _row-column wise_.
Next, each embedding was read: an _element read_, a _row read_ and a _column read_.
The expression used to read from each of the three embeddings is the same and so is the result.
This is possible because a structure resolves up the fURI path hierarchy until it finds a match.
Once found, it then traverses within the match to resolve the remaining path segments.

.Amortized Costs in Terms of Time
[%header,width=70%,cols="l2,c1,c1,c1",role="small center"]
|===
| [.red]#embedding#              | [.red]#single-element#| [.red]#row-access#  | [.red]#column-access#
| [.red]#entry#          | \[O(1)\]       | \[O(n)\]    | \[O(m)\]
| [.red]#row#            | \[O(m)\]       | \[O(1)\]    | \[O(m)\]
| [.red]#row_column#     | \[O(1)\]       | \[O(1)\]    | \[O(1)\]
|===

The different embeddings also have different space costs, where space is defined as the amount of data accessed (i.e. retrieved from the structure) in order to satisfy the resolution of the respective fURI.

.Amortized Costs in Terms of Space
[.center]
[%header,width=70%,cols="l2,c1,c1,c1",role="small center"]
|===
| [.red]#embedding#              | [.red]#single-element# | [.red]#row-access#    | [.red]#column-access#
| [.red]#entry#          | \[O(1)\]       | \[O(n)\]      | \[O(m)\]
| [.red]#row#            | \[O(n)\]       | \[O(n)\]      | \[O(n+m)\]
| [.red]#row_column#     | \[O(n+m)\]     | \[O(n+m)\]    | \[O(n+m)\]
|===

[discrete]
=== coefficients

[cols="3a,3a,3",separator=🧱,options=header,role="table-bordered small center"]
|===
🧱 [.red]#coefficient# 🧱 [.red]#shorthand# 🧱 [.red]#name#
🧱 {0,0}       🧱 {0}       🧱 noobj
🧱 {1,1}       🧱 {1} or    🧱 an-obj
🧱 {-1,-1}     🧱 {-1}      🧱 anti-obj
🧱 {±n,±n}     🧱 {±n}      🧱 exactly ±n
🧱 {±n,±m}     🧱           🧱  between ±n and ±m

🧱 {0,1}       🧱 {?}      🧱 maybe
🧱 {1,}        🧱 {+}      🧱 some
🧱 {0,}        🧱 {*}      🧱 maybe some

🧱 {-,+}       🧱 {**}     🧱 polar maybe some
🧱 {-1,1}      🧱 {??}     🧱 polar maybe

🧱 {-1,0}      🧱 {-?}     🧱 anti-maybe
🧱 {,-1}       🧱 {-}      🧱 anti-some
🧱 {,0}        🧱 {-*}     🧱 anti-maybe some
|===