name: Continuous Integration using Java/Maven3

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    permissions: write-all
    name: Build Project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install ijhttp
        run: | 
          curl -f -s -L -o ijhttp.zip https://jb.gg/ijhttp/latest
          unzip -nq ijhttp.zip -d target/ijhttp
          rm ijhttp.zip
          echo "target/ijhttp" >> $GITHUB_PATH
      - name: Setup OpenJDK 24
        uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'oracle'
          cache: maven
      - name: Install with Maven
        run: mvn clean install --file pom.xml
      - name: Install Python Packages
        run: |
          python -m pip install --upgrade pip
          pip install websockets
      - name: Build Documentation with Maven
        run: |
          bin/metatron "[log=>info,host=><ws://127.0.0.1:8999>,boot=><examples/docs.mtron>,mode=>server]" &
          mvn site --file pom.xml
      - name: Update Dependency Graph
        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
